[package]
name = "ch8-dns-lookup-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.6"
clap = "^2.33"
trust-dns = { version = "0.16", default-features = false }

[lints.rust]
dead_code = "allow"
