[package]
name = "ch8-mget-raw-http"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.7"
clap = "2"
url = "2"
smoltcp = "0.6"
trust-dns = { version = "0.16", default-features = false }

[lints.rust]
dead_code = "allow"
