[package]
name = "chapter6"
version = "0.1.0"
edition = "2021"

[dependencies]
piston_window = "0.117"
piston2d-graphics = "0.39"
rand = "0.8"

[lints.rust]
unused = "allow"
non_camel_case_types = "allow"
